name: Uploading code to s3
on:
  push:
    # types:
    #   - closed
    # branches: ["master", "main"]

jobs:
  build-and-deploy:
    #if: ((${{ github.event_name == 'pull_request'}}) and (${{github.event.pull_request.merged }} == true)) automation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync files to S3
        run: |
            echo "${{ github.event.head_commit }}"








