name: Uploading code to s3
on:
  push:
    # types:
    #   - closed
    # branches: ["master", "main"]

jobs:
  build-and-deploy:
    #if: ((${{ github.event_name == 'pull_request'}}) and (${{github.event.pull_request.merged }} == true))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync files to S3
        run: |
          if: ${{ contains(github.event.push.head_commit.modified, 'automation/') }}; then
            echo "Changes detected in automation/ folder. Proceeding with sync."
          else
            echo "No changes detected in automation/ folder. Skipping sync."
            echo "${{ github.event.push.head_commit.modified }}"
          fi



